name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake SVG (Dark)
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Generate dark snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ibrohim0811
          outputs: dist/github-snake-dark.svg
          palette: github-dark
          color_snake: "#00ffcc"
          color_dots: "#1e1e1e #2d2d2d #3b3b3b #4a4a4a #5a5a5a" # orqa fon uchun

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
